name: Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Change host to localhost
      run: echo "export const settings = { host:\"http://localhost:3030\" };" > src/config.js
    - name: Start backend 
      run: npm run start-be &
    - name: Start frontend
      run: npm run start-fe &
    - name: Install playwright dependencies
      run: npx playwright install
    - name: Execute tests
      run: npm run test-ui

  deploy_be:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.BE_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}

  deploy_fe:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.FE_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}
