name: Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm i
    - name: Change host to localhost
      run: echo "const host = \"http://localhost:3030\";\n\nexport { host };" > src/api/host.js
    - name: Start backend 
      run: npm run start-be
    - name: Start frontend
      run: npm run start-fe
    - name: Execute tests
      run: npm run test-ui
